// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/deploy.ts";
import { AppManifest } from "../deps.ts";

const manifest = {
  "actions": {
    "play/actions/deploy.ts": $$$$$$$$$0,
  },
  "name": "play",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest satisfies AppManifest;
